Задание 3.
Reallex47/qa-automation-java pull request #3
Opened 2021-08-12 12:25 UTC by Reallex47

Сгенерирован maven-проект по шаблону mvn archetype:generae com.tinkoff.akimov1:app:1.0.0-SNAPSHOT. Используется тестовая зависимость JUnit5. Выдержан стиль кодирования и соглашения. Проект успешно собран

2021-08-12 13:47 UTC, IgorSklyar requested changes
Все супер, Ты справился с заданием, при этом есть несколько моментов, которые нужно поправить. 
Прежде всего, предлагаю в файл .gitignore поместить папку target и все файлы *.iml
и удалить из ПР все файлы из этой папки и файл.iml.  Твой проект лежит в папке **MyApp1 -**  В Java принято имена пакетов записывать только строчными буквами, чтобы избежать конфликтов с именами классов или интерфейсов. Предлагаю переименовать этот пакет на **app**
Также есть пара замечаний по стилю кода ( ниже оставил комментарии к коду)  Давай будем соблюдать Java Code Style Conventions. :)     https://www.oracle.com/technetwork/java/codeconventions-150003.pdf
Ознакомься пожалуйста с ней и в дальнейшем тебе будет проще.   
И постарайся сегодня исправить замечания.

2021-08-12 13:47 UTC, IgorSklyar commented on MyApp1/src/test/java/com/tinkoff/akimov1/AppTest.java
> +
удали лишний отступ

2021-08-12 13:48 UTC, IgorSklyar commented on MyApp1/src/test/java/com/tinkoff/akimov1/AppTest.java
> +        assertTrue( true );
в сигнатуре метода assertTrue - два лишних пробела

2021-08-12 14:44 UTC, merged

2021-08-18 09:29 UTC, neparij commented on .gitignore
> +*.iml
После окончания файла нужен перенос строки

2021-08-18 09:29 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/App.java
> +}
После окончания файла нужен перенос строки

2021-08-18 09:29 UTC, neparij commented on app/src/test/java/com/tinkoff/akimov1/AppTest.java
> +}
После окончания файла нужен перенос строки

2021-08-18 09:29 UTC, neparij commented on app/pom.xml
> +  <url>http://www.example.com</url>
Лучше убрать недостоверную информацию,. а также и остальной мусор, если он не нужен

2021-08-18 09:29 UTC, neparij commented on app/pom.xml
> +  <artifactId>MyApp1</artifactId>
Согласно д/з имя артефакта/приложения должно быть другое, не критично, но лучше так не делать — название программы должно либо отображать его суть, либо сойтись с классическим App/Applicaiton, но без всяких чисел итд – для этого существует версионирование.

2021-08-18 09:29 UTC, neparij commented on app/pom.xml
> +  <groupId>com.tinkoff.akimov1</groupId>
имя группы должно быть com.tinkoff.edu, лучше поправить, так как это нарушает требования заказчика

2021-08-18 09:29 UTC, neparij commented on app/pom.xml
> +    <maven.compiler.source>1.7</maven.compiler.source>
Мы используем Java версии не ниже 1.8, здесь мы отключаем часть функционала более свежего JDK