Задание 4. Заготовка под кредитный калькулятор
Reallex47/qa-automation-java pull request #4
Opened 2021-08-19 16:46 UTC by Reallex47

Задание 4. Заготовка под кредитный калькулятор. Проект собирается. Выдержан стиль кодирования и соглашения

2021-08-20 15:10 UTC, neparij requested changes

2021-08-20 15:10 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcController.java
> +}
Рекомендую вставлять 1 перенос строки в конце файла.

2021-08-20 15:10 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcController.java
> +package com.tinkoff.akimov1;
По условию "Application designed for testability and reuse":
- Лучше заранее заготовить пакеты для контроллеров, репозиториев, запросов, etc

2021-08-20 15:10 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcRepository.java
> +package com.tinkoff.akimov1;
По условию "Application designed for testability and reuse":
- Лучше заранее заготовить пакеты для контроллеров, репозиториев, запросов, etc

2021-08-20 15:10 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcService.java
> +package com.tinkoff.akimov1;
По условию "Application designed for testability and reuse":
- Лучше заранее заготовить пакеты для контроллеров, репозиториев, запросов, etc

2021-08-20 15:10 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcRepository.java
> +}
Рекомендую вставлять 1 перенос строки в конце файла.

2021-08-20 15:10 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcService.java
> +}
Рекомендую вставлять 1 перенос строки в конце файла.

2021-08-20 15:10 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcRepository.java
> +     *TODO persists request
```suggestion
     * TODO persists request
```

2021-08-23 12:38 UTC, neparij requested changes

2021-08-23 12:38 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcController/LoanCalcController.java
> +package com.tinkoff.akimov1.LoanCalcController;
Имя пакета должно группировать схожие по назначению классы.
Для контроллеров нужно сделать пакет controllers, например, внутри которого как раз и будут располагаться LoanCalcControoler.java, ЕщеОдинController.java и другие, которые будут добавлены в процессе написания.
В данном случае ты просто продублировал название контроллера в название пакета

2021-08-23 12:38 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcRepository/LoanCalcRepository.java
> +package com.tinkoff.akimov1.LoanCalcRepository;
```suggestion
package com.tinkoff.akimov1.repositories;
```

2021-08-23 12:38 UTC, neparij commented on app/src/main/java/com/tinkoff/akimov1/LoanCalcService/LoanCalcService.java
> +package com.tinkoff.akimov1.LoanCalcService;
аналогично

2021-08-23 13:28 UTC, IgorSklyar commented on app/src/main/java/com/tinkoff/akimov1/Services/LoanCalcService.java
> +package com.tinkoff.akimov1.Services;
в java именование пакетов должно быть строчными буквами. Пройдись, плиз, по всем пакетам и поправь

2021-08-23 13:29 UTC, IgorSklyar requested changes
исправь пожалуйста замечания по именованию пакетов

2021-08-23 13:40 UTC, IgorSklyar approved these changes
все супер! продолжай в том же духе!)

2021-08-23 13:40 UTC, merged